package das.tools.np.gui.menu;

public enum ApplicationAction {
    NM_ADD, NM_UPDATE, NM_UPDATE_UNCOMPLETED, NM_MOVE_TO_ARCHIVE, NM_ADD_TO_CUSTOM_LIST, NM_RESTORE_FROM_ARCHIVE, NM_EXIT,
    ED_NEW_GROUP, ED_EDIT_GROUPS, ED_PHONES, ED_SEARCH_OPTIONS, ED_SEARCH, ED_CONFIGURATION,
    VM_NUMBERS, VM_GROUPS, VM_CALENDAR_CREATE, VM_CALENDAR_UPDATE,
    FM_ALL, FM_IN, FM_OUT, FM_UNCOMPLETED,
    VW_DETAILED_INFO, VW_SHOW_LOG,
    PG_LOAD_PLUGINS,
    WN_CUSTOM_LIST, WN_ARCHIVED_LIST, WN_CASCADE, WN_CLOSE_ALL,
    HP_ABOUT,
    LOG_COPY, LOG_CLEAR
}
